---
- name: Run a hub container
  docker_container:
    name: "{{ docker_selenium_hub_name }}"
    image: "{{ docker_selenium_hub_image }}:{{ docker_selenium_tag }}"
    pull: "{{ docker_selenium_pull_image }}"
    state: "{{ docker_selenium_state }}"
    ports: "{{ docker_selenium_hub_port }}"

- name: Run node containers
  include_tasks: container.yml
  with_items:
    - "{{ docker_selenium_nodes }}"
  loop_control:
    loop_var: docker_selenium_node
